name: Bot Node.js CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - '**/*.md'
      - '*.md'
      - '.gitignore'
      - ".github/**"

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

  deploy:
    needs: build
    runs-on: [self-hosted, x64, linux, bot, production, nodejs]

    steps:
    - name: Merge changes
      run: git pull origin main --depth=100
    - run: npm install
